### ISSUE TITLE
Can't find ADL, monitoring disabled

### ISSUE THREAD

**Issue by sammy007** [decred/cgminer#11] opened 2016-02-05 09:00 UTC
Previously I built it without problems on 14.04 LTS by copying headers to ADL_SDK directory. After several "fixes" in master it's no longer possible.

My command: CFLAGS="-O2 -Wall -march=native" ./configure --enable-opencl

**Comment by jcvernaleo** [comment] 2016-02-05 15:19
@sammy007 in theory that should be fixed with the most recent commit c172a7a62455fae62afdc7995021f5c046aab9d7.  What commit are you on?

@jolan said it worked for him on that commit.  If you are on the most recent and still hit that, could you post your config.log?

**Comment by chappjc** [comment] 2016-02-05 17:30
Reran autoconf after sync?  Works in arch and windows as long as the adl headers are in place.  ADL detection while cross-compiling was broken out of the gates...  shooting to support native and cross compiling.
If there are differences on other systems, then we could snag [this bit of Wolf's PR](https://github.com/wolf9466/cgminer/commit/4adc167e8e673206f90e22fd10e996b819533f1e#diff-67e997bcfdac55191033d57a16d1408aR201) that adds a flag to skip the check entirely.

@jcvernaleo  Assuming you successfully used the current source to generate the releases posted in the last day?

**Comment by sammy007** [comment] 2016-02-05 20:58
I cloned repo from scratch, repeated previous steps and submitted an issue.

**Comment by jolan** [comment] 2016-02-06 04:39
Please provide a config.log so we can look into it as it works for myself and @chappjc.

**Comment by sammy007** [comment] 2016-02-06 06:03
```
configure:16207: checking for ADL_SDK/adl_sdk.h
In file included from ./ADL_SDK/adl_sdk.h:19:0,
./ADL_SDK/adl_structures.h:2346:5: error: unknown type name 'bool'
./ADL_SDK/adl_structures.h:2352:5: error: unknown type name 'bool'
| #include <ADL_SDK/adl_sdk.h>
ac_cv_header_ADL_SDK_adl_sdk_h=no
ADL_CPPFLAGS=''
```

I added:

``` c
#include <stdbool.h> 
```

to adl_structures.h and configure found ADL and I compiled cgminer successfully. Please fix.

My configure command: <code>CFLAGS="-O2 -Wall -march=native" ./configure --enable-opencl</code>

**Comment by chappjc** [comment] 2016-02-06 06:11
Ah, <s>I think your compiler is pre-C99</s> (or stdbool.h is not pulled in with `AC_INCLUDES_DEFAULT` by your autoconf).  I'm using GCC 5.3 in each of my build configurations, so maybe I get `bool` for free.  What is yours?  In any case, apparently this is why miner.h includes stdbool.h.

**Comment by sammy007** [comment] 2016-02-06 06:12
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)

**Comment by sammy007** [comment] 2016-02-06 06:14
There is no 5.x GCC in ubuntu LTS, LTS is "standard", previously I successfully compiled this cgminer so I guess it was broken in latest fixes and can be fixed with easy. Otherwise people will be confused.

**Comment by chappjc** [comment] 2016-02-06 06:18
Either the check can be disabled ([like this perhaps](https://github.com/wolf9466/cgminer/commit/4adc167e8e673206f90e22fd10e996b819533f1e#diff-67e997bcfdac55191033d57a16d1408aR201)) or the stdbool.h can be included in the check as you did.

Anyway, sorry about that.  I'll have to test on a 14.04 vbox or at least with CC=gcc-4.8 before suggesting any edits in the future.  The upcoming 16.04 will be LTS so hopefully that will become more mainstream in time, but that's an aside.

**Comment by chappjc** [comment] 2016-02-06 07:36
Well, I was sure I would be able to reproduce the issue in a fresh Ubuntu 14.04 vbox, but I got this:

<pre>Configuration` Options Summary:
  libcurl(GBT+getwork).: Enabled: -lcurl  
  curses.TUI...........: FOUND: -lncurses
  OpenCL...............: FOUND. GPU mining support enabled
  scrypt...............: Disabled
  ADL..................: SDK found, GPU monitoring support enabled
  Avalon.ASICs.........: Disabled
  BFL.ASICs............: Disabled
  KnC.ASICs............: Disabled
  BitForce.FPGAs.......: Disabled
  BitFury.ASICs........: Disabled
  Hashfast.ASICs.......: Disabled
  BlackArrow.ASICs.....: Disabled
  Icarus.ASICs/FPGAs...: Disabled
  Klondike.ASICs.......: Disabled
  ModMiner.FPGAs.......: Disabled
Compilation............: make (or gmake)
  CPPFLAGS.............: 
  CFLAGS...............: -g -O2
  LDFLAGS..............:  -lpthread
  LDADD................: -ldl -lcurl   compat/jansson-2.5/src/.libs/libjansson.a -lpthread -L/home/jon/SDK/AMDAPPSDK-3.0/lib/x86_64 -lOpenCL    -lm  -lrt
Installation...........: make install (as root if needed, with 'su' or 'sudo')
  prefix...............: /usr/local
jon@ubuntu-trusty-vm:~/github/cgminer-chappjc$ uname -a
Linux ubuntu-trusty-vm 3.13.0-77-generic #121-Ubuntu SMP Wed Jan 20 10:50:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
jon@ubuntu-trusty-vm:~/github/cgminer-chappjc$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
</pre>

Maybe I added the "backports" or "proposed" repositories, nothing that wasn't from Canonical though.  Whatever the issue is, I made [a branch for the proposed fix](https://github.com/chappjc/cgminer/commit/7972a5a454ddca292e00448f672b956758edec11).  @sammy007  Can you see if that works for you?  Thanks.

**Comment by sammy007** [comment] 2016-02-06 08:51
> Can you see if that works for you? Thanks.

No, it does not.

**Comment by sammy007** [comment] 2016-02-06 08:56
Ah, my bad. I forgot to re-run autogen.sh, it works now with this patch.

**Comment by chappjc** [comment] 2016-02-06 16:01
Thanks for checking.  Maybe one of the devs, @jcvernaleo or @jolan or someone else can decide if the PR ([#12](https://github.com/decred/cgminer/pull/12)) is acceptable?  I branched it before resyncing, so there are a bunch of commits in the list, but the end result is [1 line](https://github.com/decred/cgminer/pull/12/files) changed.

**Comment by jcvernaleo** [comment] 2016-02-07 13:36
@chappjc I'm looking at/testing your PR now.

**Comment by jcvernaleo** [comment] 2016-02-07 15:00
Since everyone said @chappjc's PR fixes this and it seems good to me too, I'm closing.  This was dealt with by commit 72afa18.  Feel free to reopen if problems continue.

**Closed as completed by jcvernaleo** 2016-02-07 15:00 UTC
